# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Bibliography', folder: 'pages', file: 'bibliography.html'}
- {name: 'Data', folder: 'pages', file: 'data.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/ecosistema'}
- {icon: 'facebook', link: 'https://www.facebook.com/ecosistemaurbano/'}
- {icon: 'instagram', link: 'https://instagram.com/ecosistemaurbano'}
- {icon: 'envelope', link: 'mailto:info@ecosistemaurbano.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
